import { getDb } from "./db";
import { missions } from "../drizzle/schema";

const MISSIONS_DATA = [
  {
    title: "Document Infrastructure Decay",
    description: "Photograph and document deteriorating infrastructure in your area (bridges, roads, buildings). Upload evidence to the Reality Stream.",
    missionType: "infrastructure",
    difficulty: "easy",
    rewardTruthCredits: 50,
    rewardXp: 25,
    locationLatitude: 40.7128,
    locationLongitude: -74.0060,
    locationRadiusMeters: 5000,
    validationCriteria: "Clear documentation of infrastructure condition with location verification",
  },
  {
    title: "Environmental Impact Assessment",
    description: "Record video evidence of environmental issues (pollution, litter, habitat destruction). Document the location and severity.",
    missionType: "environmental",
    difficulty: "medium",
    rewardTruthCredits: 100,
    rewardXp: 50,
    locationLatitude: 40.7580,
    locationLongitude: -73.9855,
    locationRadiusMeters: 10000,
    validationCriteria: "Video evidence with clear environmental impact and location data",
  },
  {
    title: "Civic Engagement Verification",
    description: "Capture evidence of civic participation (voting locations, community meetings, public events). Verify community involvement.",
    missionType: "civic",
    difficulty: "easy",
    rewardTruthCredits: 75,
    rewardXp: 30,
    locationLatitude: 40.7489,
    locationLongitude: -73.9680,
    locationRadiusMeters: 8000,
    validationCriteria: "Evidence of civic participation with timestamp and location",
  },
  {
    title: "Social Service Documentation",
    description: "Document social services in your area (shelters, food banks, community centers). Verify their operations and impact.",
    missionType: "social",
    difficulty: "medium",
    rewardTruthCredits: 100,
    rewardXp: 45,
    locationLatitude: 40.7614,
    locationLongitude: -73.9776,
    locationRadiusMeters: 12000,
    validationCriteria: "Documentation of social services with operational status",
  },
  {
    title: "Emergency Response Verification",
    description: "Document emergency services in action (fire departments, ambulances, disaster response). Capture real-world emergency management.",
    missionType: "emergency",
    difficulty: "hard",
    rewardTruthCredits: 200,
    rewardXp: 100,
    locationLatitude: 40.7505,
    locationLongitude: -73.9972,
    locationRadiusMeters: 15000,
    validationCriteria: "Real-time emergency response documentation with location verification",
  },
  {
    title: "Public Health Monitoring",
    description: "Record evidence of public health initiatives (vaccination sites, health clinics, wellness programs). Document community health efforts.",
    missionType: "infrastructure",
    difficulty: "medium",
    rewardTruthCredits: 125,
    rewardXp: 60,
    locationLatitude: 40.7282,
    locationLongitude: -73.7949,
    locationRadiusMeters: 7000,
    validationCriteria: "Evidence of public health services with location and operational status",
  },
  {
    title: "Transportation System Audit",
    description: "Document public transportation conditions (buses, trains, bike lanes). Record evidence of system functionality and issues.",
    missionType: "infrastructure",
    difficulty: "easy",
    rewardTruthCredits: 60,
    rewardXp: 35,
    locationLatitude: 40.7549,
    locationLongitude: -73.9840,
    locationRadiusMeters: 6000,
    validationCriteria: "Transportation system documentation with operational status",
  },
  {
    title: "Wildlife Habitat Monitoring",
    description: "Capture video evidence of local wildlife and their habitats. Document biodiversity and environmental conditions.",
    missionType: "environmental",
    difficulty: "medium",
    rewardTruthCredits: 110,
    rewardXp: 55,
    locationLatitude: 40.7829,
    locationLongitude: -73.9654,
    locationRadiusMeters: 9000,
    validationCriteria: "Wildlife documentation with habitat assessment and location",
  },
  {
    title: "Community Art Documentation",
    description: "Record evidence of public art, murals, and cultural installations. Document community creative expression.",
    missionType: "civic",
    difficulty: "easy",
    rewardTruthCredits: 70,
    rewardXp: 40,
    locationLatitude: 40.7505,
    locationLongitude: -73.9680,
    locationRadiusMeters: 5000,
    validationCriteria: "Clear documentation of public art with location verification",
  },
  {
    title: "Disaster Recovery Verification",
    description: "Document recovery efforts from natural disasters or emergencies. Record community resilience and reconstruction.",
    missionType: "emergency",
    difficulty: "hard",
    rewardTruthCredits: 250,
    rewardXp: 125,
    locationLatitude: 40.7282,
    locationLongitude: -74.0076,
    locationRadiusMeters: 20000,
    validationCriteria: "Comprehensive disaster recovery documentation with before/after evidence",
  },
  {
    title: "Water Quality Assessment",
    description: "Test and document water quality in local waterways (rivers, lakes, streams). Record clarity, pollution, and aquatic life.",
    missionType: "environmental",
    difficulty: "medium",
    rewardTruthCredits: 90,
    rewardXp: 45,
    locationLatitude: 40.7614,
    locationLongitude: -73.9776,
    locationRadiusMeters: 8000,
    validationCriteria: "Water quality documentation with location and condition assessment",
  },
  {
    title: "Air Quality Monitoring",
    description: "Document air quality conditions in your area. Record visible pollution, weather conditions, and atmospheric clarity.",
    missionType: "environmental",
    difficulty: "easy",
    rewardTruthCredits: 65,
    rewardXp: 32,
    locationLatitude: 40.7505,
    locationLongitude: -73.9972,
    locationRadiusMeters: 7000,
    validationCriteria: "Air quality observations with timestamp and location verification",
  },
  {
    title: "Public Park Maintenance Audit",
    description: "Inspect and document the condition of public parks (cleanliness, equipment, accessibility). Record maintenance issues.",
    missionType: "civic",
    difficulty: "easy",
    rewardTruthCredits: 55,
    rewardXp: 28,
    locationLatitude: 40.7829,
    locationLongitude: -73.9654,
    locationRadiusMeters: 5000,
    validationCriteria: "Park condition documentation with maintenance status",
  },
  {
    title: "Street Light Functionality Check",
    description: "Document the status of street lighting in your area. Record working and non-functional lights for safety assessment.",
    missionType: "infrastructure",
    difficulty: "easy",
    rewardTruthCredits: 50,
    rewardXp: 25,
    locationLatitude: 40.7282,
    locationLongitude: -73.7949,
    locationRadiusMeters: 6000,
    validationCriteria: "Street light status documentation with location mapping",
  },
  {
    title: "Homeless Support Services Verification",
    description: "Document homeless support services and shelters. Verify operational status and community impact.",
    missionType: "social",
    difficulty: "medium",
    rewardTruthCredits: 120,
    rewardXp: 60,
    locationLatitude: 40.7549,
    locationLongitude: -73.9840,
    locationRadiusMeters: 10000,
    validationCriteria: "Shelter and service documentation with operational verification",
  },
  {
    title: "Accessibility Audit",
    description: "Assess accessibility features in public spaces (ramps, elevators, sidewalks). Document barriers and accommodations.",
    missionType: "civic",
    difficulty: "medium",
    rewardTruthCredits: 85,
    rewardXp: 42,
    locationLatitude: 40.7128,
    locationLongitude: -74.0060,
    locationRadiusMeters: 8000,
    validationCriteria: "Accessibility features documentation with barrier assessment",
  },
  {
    title: "Food Security Verification",
    description: "Document food banks, community gardens, and food distribution centers. Verify food security initiatives.",
    missionType: "social",
    difficulty: "medium",
    rewardTruthCredits: 110,
    rewardXp: 55,
    locationLatitude: 40.7580,
    locationLongitude: -73.9855,
    locationRadiusMeters: 9000,
    validationCriteria: "Food security resource documentation with availability verification",
  },
  {
    title: "Graffiti and Vandalism Report",
    description: "Document graffiti and vandalism in public areas. Record location and severity for community safety assessment.",
    missionType: "civic",
    difficulty: "easy",
    rewardTruthCredits: 40,
    rewardXp: 20,
    locationLatitude: 40.7489,
    locationLongitude: -73.9680,
    locationRadiusMeters: 5000,
    validationCriteria: "Vandalism documentation with location and severity rating",
  },
  {
    title: "Pothole and Road Hazard Mapping",
    description: "Identify and document potholes, road hazards, and pavement damage. Create a safety hazard map.",
    missionType: "infrastructure",
    difficulty: "easy",
    rewardTruthCredits: 55,
    rewardXp: 27,
    locationLatitude: 40.7614,
    locationLongitude: -73.9776,
    locationRadiusMeters: 6000,
    validationCriteria: "Road hazard documentation with location coordinates",
  },
  {
    title: "Tree Health and Urban Forest Monitoring",
    description: "Assess the health of trees in urban areas. Document disease, damage, and environmental conditions.",
    missionType: "environmental",
    difficulty: "medium",
    rewardTruthCredits: 95,
    rewardXp: 47,
    locationLatitude: 40.7829,
    locationLongitude: -73.9654,
    locationRadiusMeters: 8000,
    validationCriteria: "Tree health assessment with location and condition documentation",
  },
  {
    title: "Noise Pollution Documentation",
    description: "Record and document noise pollution sources (traffic, construction, industrial). Assess noise levels and impact.",
    missionType: "environmental",
    difficulty: "medium",
    rewardTruthCredits: 80,
    rewardXp: 40,
    locationLatitude: 40.7505,
    locationLongitude: -73.9972,
    locationRadiusMeters: 7000,
    validationCriteria: "Noise pollution documentation with source identification",
  },
  {
    title: "Business District Vitality Assessment",
    description: "Document the condition and activity of local businesses. Record occupancy rates and community engagement.",
    missionType: "civic",
    difficulty: "medium",
    rewardTruthCredits: 100,
    rewardXp: 50,
    locationLatitude: 40.7282,
    locationLongitude: -73.7949,
    locationRadiusMeters: 6000,
    validationCriteria: "Business district documentation with occupancy and activity assessment",
  },
  {
    title: "School and Education Facility Audit",
    description: "Document schools and educational facilities. Verify condition, accessibility, and community resources.",
    missionType: "infrastructure",
    difficulty: "medium",
    rewardTruthCredits: 115,
    rewardXp: 57,
    locationLatitude: 40.7549,
    locationLongitude: -73.9840,
    locationRadiusMeters: 8000,
    validationCriteria: "School facility documentation with condition and accessibility assessment",
  },
  {
    title: "Utility Infrastructure Inspection",
    description: "Document utility infrastructure (power lines, water mains, telecommunications). Record condition and maintenance needs.",
    missionType: "infrastructure",
    difficulty: "hard",
    rewardTruthCredits: 150,
    rewardXp: 75,
    locationLatitude: 40.7128,
    locationLongitude: -74.0060,
    locationRadiusMeters: 10000,
    validationCriteria: "Utility infrastructure documentation with condition assessment",
  },
  {
    title: "Pedestrian Safety Verification",
    description: "Assess pedestrian safety features (crosswalks, signals, sidewalk conditions). Document safety hazards and improvements.",
    missionType: "civic",
    difficulty: "medium",
    rewardTruthCredits: 90,
    rewardXp: 45,
    locationLatitude: 40.7580,
    locationLongitude: -73.9855,
    locationRadiusMeters: 7000,
    validationCriteria: "Pedestrian safety documentation with hazard identification",
  },
  {
    title: "Community Event Documentation",
    description: "Capture evidence of community events and gatherings. Document attendance, activities, and community engagement.",
    missionType: "civic",
    difficulty: "easy",
    rewardTruthCredits: 75,
    rewardXp: 37,
    locationLatitude: 40.7489,
    locationLongitude: -73.9680,
    locationRadiusMeters: 6000,
    validationCriteria: "Community event documentation with attendance and activity details",
  },
  {
    title: "Waste Management System Audit",
    description: "Document waste management infrastructure (trash collection, recycling, hazardous waste). Verify system functionality.",
    missionType: "infrastructure",
    difficulty: "medium",
    rewardTruthCredits: 105,
    rewardXp: 52,
    locationLatitude: 40.7614,
    locationLongitude: -73.9776,
    locationRadiusMeters: 8000,
    validationCriteria: "Waste management documentation with system functionality assessment",
  },
  {
    title: "Renewable Energy Installation Verification",
    description: "Document renewable energy installations (solar panels, wind turbines). Verify functionality and community impact.",
    missionType: "infrastructure",
    difficulty: "hard",
    rewardTruthCredits: 180,
    rewardXp: 90,
    locationLatitude: 40.7829,
    locationLongitude: -73.9654,
    locationRadiusMeters: 12000,
    validationCriteria: "Renewable energy installation documentation with functionality verification",
  },
  {
    title: "Mental Health Services Mapping",
    description: "Document mental health services and support resources in your area. Verify accessibility and availability.",
    missionType: "social",
    difficulty: "medium",
    rewardTruthCredits: 125,
    rewardXp: 62,
    locationLatitude: 40.7505,
    locationLongitude: -73.9972,
    locationRadiusMeters: 9000,
    validationCriteria: "Mental health services documentation with accessibility verification",
  },
];

export async function seedMissions() {
  try {
    const db = await getDb();
    if (!db) {
      console.error("Database connection failed");
      return;
    }

    console.log("Seeding missions...");

    // Clear existing missions
    await db.delete(missions);
    console.log("Cleared existing missions");

    // Insert new missions
    for (const mission of MISSIONS_DATA) {
      try {
        await db.insert(missions).values({
          title: mission.title,
          description: mission.description,
          missionType: mission.missionType as any,
          difficulty: mission.difficulty as any,
          locationLatitude: mission.locationLatitude as any,
          locationLongitude: mission.locationLongitude as any,
          locationRadiusMeters: mission.locationRadiusMeters,
          rewardTruthCredits: mission.rewardTruthCredits,
          rewardXp: mission.rewardXp,
          validationCriteria: mission.validationCriteria,
          createdBy: 1, // System admin
        });
        console.log(`✓ Created mission: ${mission.title}`);
      } catch (e) {
        console.error(`Failed to create mission ${mission.title}:`, e);
      }
    }

    console.log(`\n✅ Successfully seeded ${MISSIONS_DATA.length} missions`);
  } catch (error) {
    console.error("Error seeding missions:", error);
    throw error;
  }
}

// Run if this is the main module
if (import.meta.url === `file://${process.argv[1]}`) {
  seedMissions()
    .then(() => process.exit(0))
    .catch((error) => {
      console.error(error);
      process.exit(1);
    });
}
